import "../styles/globals.scss";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import styles from "./layout.module.scss";
import { Header } from "@/components/common/header/Header";

const roboto = Roboto({ weight: ["400", "700", "300"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
